AllCops:
  TargetRubyVersion: 2.3
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 300
Metrics/BlockLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/AbcSize:
  Max: 50
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
